#!/usr/bin/env python3
"""The paper's tables must be generated, and must agree with the diagnostics.

Two failure modes these guard against. First, a table that quietly drops an arm
or a family, which is how a paper ends up reporting the flattering subset.
Second, a table hand-edited into agreement with prose -- every file therefore
has to carry the generator's banner.

The values themselves are checked against `diagnostics.md`'s own figures rather
than against constants invented here, so a rerun that changes a number fails
loudly instead of silently propagating into the manuscript.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
TABLES = ROOT / "paper" / "tables"
GEN = ROOT / "tools" / "make_paper_tables.py"


@pytest.fixture(scope="module", autouse=True)
def _render():
    subprocess.run([sys.executable, str(GEN)], cwd=ROOT, check=True)


def _t(name: str) -> str:
    return (TABLES / name).read_text()


def test_every_table_is_generated_not_hand_edited():
    files = sorted(TABLES.glob("*.tex"))
    assert files, "no tables rendered"
    for p in files:
        assert p.read_text().startswith("% GENERATED by"), p.name


def test_task_completion_has_both_metrics_all_arms_and_the_null():
    t = _t("t2_task_completion.tex")
    for arm in ("Ours", "MaskGIT-flat", "3D U-Net", "3D CVAE"):
        assert arm in t, f"{arm} missing from T2"
    assert "Site AP" in t and "Voxel AP" in t
    # The seen-recording site-map null is a ROW, not a footnote: every learned
    # arm loses to it, and a table that omits it overstates the result.
    assert "recording site map, seen" in t
    assert "recording site map, unseen" in t
    # Its free-generation values, site and voxel. Pinned so the row cannot be
    # emitted empty. Updated 2026-08-29 from 0.7205/0.0869, which were measured
    # under the old 12/8-batch prefix budget; at the full 70-batch protocol the
    # same row reads 0.6796/0.0670. If these need changing again, confirm the
    # eval budget moved before editing them -- a silent drift here would mean
    # the table is being regenerated from something other than the pinned
    # protocol.
    assert "0.6796" in t and "0.0670" in t


def test_generation_table_has_four_families_six_arms_and_per_arm_nulls():
    t = _t("t3_generation_families.tex")
    for fam in ("Conditional accuracy", "Adherence", "Spatial placement",
                "Marginal realism"):
        assert fam in t, f"family {fam} missing from T3"
    # Four families x six arms, each carrying its own bracketed null.
    assert t.count("\\emph{[") == 24, t.count("\\emph{[")


def test_generation_table_matches_the_diagnostics_it_was_derived_from():
    """The table and diagnostics.md must not be able to disagree."""
    src = json.loads(
        (ROOT / "reports" / "external_baselines"
         / "generation_families.json").read_text())
    t = _t("t3_generation_families.tex")
    for fam, blk in src["families"].items():
        v = blk["arms"]["Ours (4C+soft)"]["global_full_local"]
        assert f"{v:.4f}" in t, f"{fam}: {v:.4f} not in rendered table"


def test_prior_null_table_quotes_median_rank_and_beats_the_hardest_rung():
    t = _t("t4c_prior_nulls.tex")
    assert "median rank" in t
    # The ladder must be present in full: beating `uniform` is worth nothing,
    # and a table showing only the easy rungs would say nothing.
    for rung in ("uniform", "global marginal", "per-recording marginal",
                 "per-recording $\\times$ position"):
        assert rung in t, f"null rung {rung!r} missing"


def test_motif_reuse_table_never_shows_the_size_confounded_jaccard():
    """The raw overlap tracks sampling effort at r = +0.96 and the analysis
    marks it unquotable. Rendering it into a paper table would undo that."""
    d = json.loads(
        (ROOT / "reports" / "analysis_motif_reuse.json").read_text())
    t = _t("t5_motif_reuse.tex")
    raw = d["jaccard_raw_SIZE_CONFOUNDED"]
    for k in ("mean_within_organoid", "mean_within_slice", "mean_cross_prep"):
        assert f"{raw[k]:.4f}" not in t, (
            f"raw {k} = {raw[k]:.4f} leaked into the paper table")
    # The rarefied ones, and the null they must be read against, are present.
    jr = d["jaccard_rarefied"]
    for k in ("mean_within_organoid", "mean_within_slice", "mean_cross_prep"):
        assert f"{jr[k]:.4f}" in t
    assert f"{jr['null_mean']:.4f}" in t
