#!/usr/bin/env python3
"""The paper's tables must be generated, and must agree with the diagnostics.

Two failure modes these guard against. First, a table that quietly drops an arm
or a family, which is how a paper ends up reporting the flattering subset.
Second, a table hand-edited into agreement with prose -- every file therefore
has to carry the generator's banner.

The values themselves are checked against `diagnostics.md`'s own figures rather
than against constants invented here, so a rerun that changes a number fails
loudly instead of silently propagating into the manuscript.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

from MAGVIT_project.tools.tests._release_guard import needs_paper, needs_reports

# The release omits the manuscript and the report artifacts;
# absent material skips, present-but-wrong still fails.
pytestmark = [needs_paper, needs_reports]


ROOT = Path(__file__).resolve().parents[2]
TABLES = ROOT / "paper" / "tables"
GEN = ROOT / "tools" / "make_paper_tables.py"


@pytest.fixture(scope="module", autouse=True)
def _render():
    subprocess.run([sys.executable, str(GEN)], cwd=ROOT, check=True)


def _t(name: str) -> str:
    return (TABLES / name).read_text()


def test_every_table_is_generated_not_hand_edited():
    files = sorted(TABLES.glob("*.tex"))
    assert files, "no tables rendered"
    for p in files:
        assert p.read_text().startswith("% GENERATED by"), p.name


def test_task_completion_has_both_metrics_all_arms_and_the_null():
    t = _t("t2_task_completion.tex")
    for arm in ("Ours", "MaskGIT-flat", "3D U-Net", "3D CVAE"):
        assert arm in t, f"{arm} missing from T2"
    assert "Site AP" in t and "Voxel AP" in t
    # The seen-assay site-map null is a ROW, not a footnote: every learned
    # arm loses to it, and a table that omits it overstates the result.
    assert "assay site map, seen" in t
    assert "assay site map, unseen" in t
    # Its free-generation values, site and voxel. Pinned so the row cannot be
    # emitted empty. Updated 2026-08-29 from 0.7205/0.0869, which were measured
    # under the old 12/8-batch prefix budget; at the full 70-batch protocol the
    # same row reads 0.6796/0.0670. If these need changing again, confirm the
    # eval budget moved before editing them -- a silent drift here would mean
    # the table is being regenerated from something other than the pinned
    # protocol.
    assert "0.6796" in t and "0.0670" in t


def test_generation_table_has_four_families_six_arms_and_per_arm_nulls():
    t = _t("t3_generation_families.tex")
    for fam in ("Descriptor error", "Adherence", "Spatial placement",
                "Marginal realism"):
        assert fam in t, f"family {fam} missing from T3"
    # Four families x six arms, each carrying its own bracketed null.
    assert t.count("\\emph{[") == 24, t.count("\\emph{[")


def test_generation_table_matches_the_diagnostics_it_was_derived_from():
    """The table and diagnostics.md must not be able to disagree."""
    src = json.loads(
        (ROOT / "reports" / "external_baselines"
         / "generation_families.json").read_text())
    t = _t("t3_generation_families.tex")
    for fam, blk in src["families"].items():
        v = blk["arms"]["Ours (4C+soft)"]["global_full_local"]
        assert f"{v:.4f}" in t, f"{fam}: {v:.4f} not in rendered table"


def test_prior_null_table_quotes_median_rank_and_beats_the_hardest_rung():
    t = _t("t4c_prior_nulls.tex")
    assert "median rank" in t
    # The ladder must be present in full: beating `uniform` is worth nothing,
    # and a table showing only the easy rungs would say nothing.
    for rung in ("uniform", "global marginal", "per-assay marginal",
                 "per-assay $\\times$ position"):
        assert rung in t, f"null rung {rung!r} missing"


def test_motif_reuse_table_never_shows_the_size_confounded_jaccard():
    """The raw overlap tracks sampling effort at r = +0.96 and the analysis
    marks it unquotable. Rendering it into a paper table would undo that."""
    d = json.loads(
        (ROOT / "reports" / "analysis_motif_reuse.json").read_text())
    t = _t("t5_motif_reuse.tex")
    raw = d["jaccard_raw_SIZE_CONFOUNDED"]
    for k in ("mean_within_organoid", "mean_within_slice", "mean_cross_prep"):
        assert f"{raw[k]:.4f}" not in t, (
            f"raw {k} = {raw[k]:.4f} leaked into the paper table")
    # The rarefied ones, and the null they must be read against, are present.
    jr = d["jaccard_rarefied"]
    for k in ("mean_within_organoid", "mean_within_slice", "mean_cross_prep"):
        assert f"{jr[k]:.4f}" in t
    assert f"{jr['null_mean']:.4f}" in t


def test_stage_chronology_lists_every_stage_with_its_handoff():
    """Section 4.5 leans on this table instead of narrating the chronology.

    A stage missing here would read as a stage the paper does not have, so the
    generator raises rather than emitting a short table -- this asserts the
    rendered result as well.
    """
    t = _t("t1_stages.tex")
    for stage in ("1", "2A", "3", "4A", "4B", "4C"):
        assert f"\n{stage} &" in t, f"stage {stage} missing from the chronology"
    # Each row must say what the stage hands the next one; a chronology
    # without the hand-off does not show that nothing is trained jointly.
    assert t.count("frozen") >= 3
    assert "the activity field 4B" in t, "4C's input distribution is not stated"
    # The selection metrics moved to a footnote when the table went to four
    # columns; they must still be present somewhere in the file.
    for metric in ("MRR", "NLL", "AUPRC"):
        assert metric in t, f"selection metric {metric} dropped from the table"


def test_appendix_floats_are_not_pinned_to_here_only():
    """`[h]` alone cascades: once one float cannot be placed, every float after
    it defers too, and the tables end up in a block at the end of the document
    while their sections read as headings with nothing under them. That is what
    the appendix did -- eleven of seventeen tables landed four to nine pages
    after the text discussing them. `[htbp]` lets a float take a page top."""
    src = (ROOT / "paper" / "sections" / "99_appendix.tex").read_text()
    assert "\\begin{table}[h]" not in src, (
        "an appendix table is pinned [h]; floats will cascade to the end again")


def test_unet_spatial_map_numbers_are_the_current_ones():
    """Two different figures for the same quantity were in the appendix.

    `app:baselines` quoted 0.2126/0.0351 -- the v1 U-Net run -- while
    `app:limits` quoted 0.2757/0.0552 from the shipped diagnose artifacts.
    check_paper_numbers.py could not catch it: it verifies that a number exists
    somewhere under reports/, not that it is the number for this quantity.
    """
    import json
    pos = json.loads((ROOT / "reports" / "external_baselines"
                      / "diagnose_unet3d.json").read_text())
    nopos = json.loads((ROOT / "reports" / "external_baselines"
                        / "diagnose_unet3d_nopos.json").read_text())
    full = "global_full_local"
    a = pos["context_and_space"]["regimes"][full]["map_r_own_clip"]
    b = nopos["context_and_space"]["regimes"][full]["map_r_own_clip"]
    tex = " ".join((ROOT / "paper" / "sections" / "99_appendix.tex").read_text().split())
    assert f"{a:.4f}" in tex, f"appendix does not quote map_r with pos ({a:.4f})"
    assert f"{b:.4f}" in tex, f"appendix does not quote map_r without pos ({b:.4f})"
    for stale in ("0.2126", "0.0351"):
        assert stale not in tex, f"the v1 U-Net value {stale} is back"


def test_cvae_collapse_table_records_the_countermeasures():
    """A reviewer's first reading of "the latent collapses" is that the arm was
    under-tuned so that it would. The table has to carry both what was done
    against collapse and the outcome, read from the fit reports.
    """
    import json
    t = _t("a_cvae_collapse.tex")
    for measure in ("conditional", "free bits", "warm-up", "per channel"):
        assert measure in t, f"anti-collapse measure {measure!r} not stated"
    # Both fits, and both must still be collapsing -- if one stops, the
    # appendix's argument changes and the prose has to be re-read.
    for name in ("cvae3d", "cvae3d_nopos"):
        d = json.loads(
            (ROOT / "ckpts" / "external_baselines" / f"{name}.fit.json").read_text())
        assert d["latent_collapsed"], (
            f"{name} no longer collapses; Appendix N's argument is now wrong")
        assert f"{d['final_val_kl_per_dim']:.4f}" in t, name
    assert t.count(" yes ") == 2, "a fit is missing from the table"


def test_site_level_oracle_is_not_described_as_a_tie():
    """At site level the FLAT alphabet scores higher, not equal.

    An earlier draft called the two references "close" (0.2296 against 0.2607,
    13% apart in the peer's favour) while framing the sentence as our
    advantage being uneven. A reviewer who divides sees the peer win that axis,
    so the text has to concede it in the same breath.
    """
    import json
    ours = json.loads((ROOT / "reports" / "external_baselines"
                       / "task_eval_pipeline.json").read_text())
    flat = json.loads((ROOT / "reports" / "external_baselines"
                       / "task_eval_maskgit_flat.json").read_text())
    a = ours["tasks"]["recon"]["arms"]["oracle"]["site_mean"]
    b = flat["tasks"]["recon"]["arms"]["oracle"]["site_mean"]
    tex = " ".join((ROOT / "paper" / "sections"
                    / "05_experiments.tex").read_text().split())
    if a < b:
        assert "slightly \\emph{lower}" in tex or "lower" in tex, (
            "ours is lower at site level and the paper does not say so")
        assert "are close" not in tex, "the site-level tie framing is back"
