#!/usr/bin/env python3
"""Per-recording provenance for every assay the pipeline trains on.

The paper has to say where the data came from, and the honest answer is not the
one the archive appears to give: DANDI 000732 stamps every file with
`subject_id: U`, `age: P1D/P100Y` and one shared `session_start_time` under
`session_description: "Auto-generated by neuroconv"`. Those are conversion
defaults, so the archive collapses a cohort of at most six organoids into a
single apparent subject. This script records what the files actually contain
and leaves the unresolvable parts marked unresolvable, rather than letting a
placeholder be read as a measurement.

The signal itself is fingerprinted separately by
`tools/extract_recording_fingerprints.py`, and the byte-identical pairs it finds
are reported by `tools/check_duplicate_recordings.py`. The routing hash below
cannot see those: two recordings of one organoid share a routing configuration
whether or not they are the same recording.

Reads NWB metadata with h5py (pynwb is not installed in the pytorch env) and
never touches `acquisition/ElectricalSeries/data`, which is GB-scale.

    python tools/extract_provenance.py

Writes reports/data_provenance.json, consumed by the appendix data table.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
from glob import glob
from pathlib import Path

import h5py
import numpy as np

ROOT = Path(__file__).resolve().parents[2]          # .../organoid_data
OUT = Path("reports/data_provenance.json")

# What each dandiset is, in the words of its own metadata. Kept here rather than
# derived because the two differ in which fields they populate, and because the
# preparation type is the one thing a reader must not have to infer.
DANDISETS = {
    "000732": {
        "preparation": "human brain organoid slice",
        "experiment_description": "Intrinsic activity in human brain organoid slice",
        "lab": "Kosik Lab, UCSB",
        # Corrected 2026-09-12 by the provenance audit; the previous note
        # described a later compilation and not this deposit. See
        # docs/provenance_audit/PROVENANCE_AUDIT.md. Every asset here is a
        # MaxWell array recording of a sectioned organoid: there is no
        # whole-organoid probe recording in the corpus.
        "cohort_note": "source study (Sharf et al. 2022) reports 6 sliced "
                       "organoids, L1-L6 by array number, all from the single "
                       "iPSC line F12442.4 and one consenting tissue donor",
        "recording_to_preparation_map": "NOT RECOVERABLE from the archive",
        "published_accession": "000732 is the deposit used here and no longer "
                               "resolves in the archive; 001603 is the later "
                               "compilation that incorporates this material "
                               "alongside recordings from other studies",
    },
    "001132": {
        "preparation": "human ex vivo hippocampal slice (neurosurgical resection)",
        "experiment_description": "Multimodal evaluation of network activity and "
                                  "optogenetic interventions in human hippocampal slices",
        "lab": "NOW Lab, UCSF (institution: UCSF, UCSC)",
        "cohort_note": "dandiset covers 69 subjects; we use recordings from 2",
        "recording_to_preparation_map": "subject_id identifies the patient",
        "published_accession": "001132",
    },
}


def _jsonable(o):
    """Coerce anything h5py hands back into something json can encode.

    Applied to the whole payload rather than per field: the two dandisets
    populate different fields with different storage types (object arrays of
    bytes, numpy scalars, fixed-width strings), and a per-field fix has already
    missed two of them.
    """
    if isinstance(o, bytes):
        return o.decode()
    if isinstance(o, np.generic):
        return o.item()
    if isinstance(o, np.ndarray):
        return _jsonable(o.tolist())
    if isinstance(o, dict):
        return {str(k): _jsonable(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_jsonable(v) for v in o]
    return o


def _s(h, path):
    """A JSON-safe scalar or list from the NWB file, or None.

    Fields differ in shape between the two dandisets -- `experimenter` is a byte
    array in one and absent in the other -- so everything is normalised here
    rather than at each call site.
    """
    if path not in h:
        return None
    v = h[path][()]
    if isinstance(v, bytes):
        return v.decode()
    if isinstance(v, np.ndarray):
        if v.dtype.kind == "S":
            return [x.decode() for x in v.tolist()]
        return v.tolist()
    if isinstance(v, np.generic):
        return v.item()
    return v


def nwb_metadata(nwb_path: Path) -> dict:
    with h5py.File(nwb_path, "r") as h:
        e = h["general/extracellular_ephys/electrodes"]
        elec = np.sort(np.asarray(e["electrode"][()]))
        rx, ry = np.asarray(e["rel_x"][()]), np.asarray(e["rel_y"][()])
        es = h["acquisition/ElectricalSeries"]
        rate = None
        if "starting_time" in es:
            rate = float(es["starting_time"].attrs.get("rate", 0)) or None
        n_samples = int(es["data"].shape[0])
        return {
            "subject_id": _s(h, "general/subject/subject_id"),
            "species": _s(h, "general/subject/species"),
            "age": _s(h, "general/subject/age"),
            "sex": _s(h, "general/subject/sex"),
            "lab": _s(h, "general/lab"),
            "institution": _s(h, "general/institution"),
            "experimenter": _s(h, "general/experimenter"),
            "session_start_time": _s(h, "session_start_time"),
            "session_description": _s(h, "session_description"),
            "device": next(
                (str(h[f"general/devices/{k}"].attrs.get("description", ""))
                 for k in h.get("general/devices", {})), None),
            "n_routed_channels": int(len(elec)),
            "electrode_index_max": int(elec.max()),
            # Two recordings of the same physical preparation would share a
            # routing configuration; distinct hashes mean distinct configs, which
            # is suggestive of distinct preparations but does NOT establish it --
            # the array coordinate frame is identical hardware either way.
            "electrode_config_md5": hashlib.md5(elec.tobytes()).hexdigest()[:10],
            "footprint_um": {"x_min": float(rx.min()), "x_max": float(rx.max()),
                             "y_min": float(ry.min()), "y_max": float(ry.max())},
            "sampling_rate_hz": rate,
            "n_samples": n_samples,
            "duration_s": round(n_samples / rate, 1) if rate else None,
        }


def main() -> int:
    # The assay ordering the pipeline uses. Mirrors main.find_assays exactly:
    # enumerate(glob(...)) with no sort, so the index depends on glob order and
    # must be reproduced, not re-derived.
    assay_paths = glob(str(ROOT / "output_data/*/*/*_ecephys"))
    if not assay_paths:
        print("no assay folders found under output_data/", file=sys.stderr)
        return 1

    rows, skipped = [], []
    for idx, ap in enumerate(assay_paths):
        name = os.path.basename(ap)
        npz = glob(os.path.join(ap, "*/binary_unit_burst_*.npz"))
        dandiset = Path(ap).parts[-3]
        subject_dir = Path(ap).parts[-2]
        nwb = ROOT / dandiset / subject_dir / f"{name}.nwb"

        row = {"assay_idx": idx, "assay_name": name, "dandiset": dandiset,
               "n_burst_files": len(npz), "used_in_pipeline": len(npz) > 0,
               "nwb_present": nwb.exists()}
        if nwb.exists():
            row.update(nwb_metadata(nwb))
        row.update({k: v for k, v in DANDISETS.get(dandiset, {}).items()
                    if k in ("preparation", "lab", "experiment_description")})

        (rows if len(npz) > 0 else skipped).append(row)

    payload = {
        "n_used": len(rows),
        "n_present_but_unused": len(skipped),
        "dandisets": DANDISETS,
        "by_preparation": {
            p: sum(1 for r in rows if r.get("preparation") == p)
            for p in {r.get("preparation") for r in rows}
        },
        "biological_n_note":
            "Assay count is a RECORDING count, not a preparation count. The "
            "organoid recordings come from a cohort of at most 6 organoids and "
            "the archive does not say which recording came from which; the "
            "slice recordings come from 2 slice preparations, one per "
            "neurosurgical patient. Three organoid recordings are "
            "byte-identical duplicates of three others, so the corpus holds 28 "
            "distinct recordings under 31 indices. No split in this work is "
            "cross-preparation.",
        "array_note":
            "MaxWell Biosystems HD-MEA: 26,400 sites at 17.5 um pitch, of which "
            "1,024 can be recorded simultaneously (source study). The model "
            "canvas is the array footprint 120x220 padded to 120x224 = 26,880.",
        "used": rows,
        "present_but_unused": skipped,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(_jsonable(payload), indent=1))

    print(f"{'idx':>4}  {'assay':<52}{'prep':<10}{'subj':<8}{'age':<7}"
          f"{'sex':<4}{'chans':>6}{'dur_s':>8}  cfg")
    for r in rows:
        prep = "organoid" if r.get("dandiset") == "000732" else "slice"
        print(f"{r['assay_idx']:>4}  {r['assay_name'][:50]:<52}{prep:<10}"
              f"{str(r.get('subject_id')):<8}{str(r.get('age')):<7}"
              f"{str(r.get('sex')):<4}{r.get('n_routed_channels', 0):>6}"
              f"{r.get('duration_s') or 0:>8.0f}  {r.get('electrode_config_md5')}")
    print(f"\nused {len(rows)} | present but unused {len(skipped)}")
    for p, n in payload["by_preparation"].items():
        print(f"   {n:>3} x {p}")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
