#!/usr/bin/env python3
"""Derive the non-anonymous preprint source from the submitted main.tex.

The anonymous submission is the master. This script generates
`paper/main_preprint.tex` from it rather than keeping a second hand-edited
copy, because two copies of a nine-page paper drift and the drift is silent.

Pick the author list with `--authors 2` or `--authors 3`: authorship of the
third author was pending at submission time, and ICLR locks the author list at
the abstract deadline, so both variants are kept ready. `--authors 2` also
pulls in `acknowledgments.tex`, which thanks him instead.

Transforms, and nothing else:

  1. `\\author{Anonymous authors ...}`  ->  `\\input{authors.tex}`
     The real author block lives in `paper/authors_2.tex` or
     `paper/authors_3.tex`, neither of which is part of the anonymous bundle.
  2. `% \\iclrfinalcopy`  ->  `\\iclrfinalcopy`
     This is what makes the template typeset `\\author` at all. It also turns
     off the grey margin line numbers, which are a review aid.
  3. `\\lhead{}` inserted after `\\maketitle`.
     The template sets the running head inside `\\@maketitle`: without an
     override the final-copy branch stamps "Published as a conference paper at
     ICLR 2027" on every page, which would be false for a preprint. Issued
     after `\\maketitle` and before the first shipout, so page 1 is covered.
The reproducibility statement's one blind-only phrase is handled in the
section file itself, with `\ificlrfinal`, so both builds read from one source.

Run:  python tools/make_preprint.py --authors 3
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"

ANON_AUTHOR = r"\author{Anonymous authors \\ Paper under double-blind review}"


def build(n_authors: int) -> str:
    src = (PAPER / "main.tex").read_text(encoding="utf-8")

    if ANON_AUTHOR not in src:
        sys.exit("main.tex no longer carries the anonymous author block verbatim; "
                 "re-read this script before trusting it")
    src = src.replace(ANON_AUTHOR, "\\input{authors_%d.tex}" % n_authors)

    marker = r"% \iclrfinalcopy"
    if marker not in src:
        sys.exit("main.tex no longer carries the commented \\iclrfinalcopy line")
    line = next(l for l in src.splitlines() if l.strip().startswith(marker))
    src = src.replace(line, r"\iclrfinalcopy")

    if r"\maketitle" not in src:
        sys.exit("main.tex has no \\maketitle")
    src = src.replace(
        r"\maketitle",
        "\\maketitle\n"
        "% No venue in the running head: this is a preprint, not a published paper.\n"
        "% The rule goes too, or an empty header leaves a bare line across page 1.\n"
        "\\lhead{}\\renewcommand{\\headrulewidth}{0pt}",
        1)

    # Acknowledgments and funding sit after the statements and before the
    # bibliography, and exist only in these non-anonymous builds. Both name
    # people and institutions, so neither may reach the blind submission.
    extra = "acknowledgments.tex" if n_authors == 2 else "funding.tex"
    src = src.replace("\\bibliography{refs}",
                      "\\input{%s}\n\n\\bibliography{refs}" % extra, 1)

    return ("% GENERATED by tools/make_preprint.py from paper/main.tex -- do not edit.\n"
            "% Edit main.tex (or paper/authors.tex) and regenerate.\n" + src)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--authors", type=int, choices=(2, 3), default=3,
                    help="3 = Mostajo-Radji is an author; 2 = he is acknowledged")
    args = ap.parse_args()

    authors = PAPER / f"authors_{args.authors}.tex"
    if not authors.is_file():
        sys.exit(f"missing {authors.relative_to(ROOT)}")

    out = PAPER / "main_preprint.tex"
    out.write_text(build(args.authors), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} using {authors.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
