#!/usr/bin/env python3
"""Render the paper's tables to LaTeX from the committed report artifacts.

Same rule as `external_baselines/diagnose_table.py`: no number is typed into
prose or into a `.tex` file by hand. Every cell here is read from a JSON file in
`reports/`, so a table cannot drift from the run that produced it, and a
reviewer's question about any cell resolves to a file path.

    python tools/make_paper_tables.py

Writes paper/tables/*.tex, each a bare `tabular` meant to be `\\input` inside a
float, so the caption and label live with the surrounding text.
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("paper/tables")
EB = Path("reports/external_baselines")

# Display names, in the order the paper argues. Ours first, then the learned
# peer, then the two conv arms, then the lookups -- which are ceilings and are
# marked as such rather than being allowed to win a bolded comparison.
ARMS = [("pipeline", "Ours"), ("maskgit_flat", "MaskGIT-flat"),
        ("unet3d", "3D U-Net$^\\dagger$"), ("cvae3d", "3D CVAE"),
        ("dg", "\\emph{ref} Dich.\\ Gaussian"), ("glm", "\\emph{ref} Coupled GLM")]


def _esc(s: str) -> str:
    # The dagger arrives as a literal U+2020 in the diagnostics labels. Times
    # has no glyph for it, so it silently vanished from the ladder table under
    # XeTeX and would need inputenc to survive pdflatex at all. Emit the
    # control sequence instead, matching how the other tables spell it.
    return (str(s).replace("_", "\\_").replace("%", "\\%")
            .replace("&", "\\&").replace("\u2020", "$^\\dagger$"))


# Family A is a z-scored error, not a rate: it is unbounded above, lower is
# better, and 1.0 is the error of an unrelated clip. "Accuracy" invites the
# opposite reading on every count, so the paper renames it at the presentation
# layer. The JSON key stays as diagnose_table emits it -- renaming the artifact
# would orphan every diagnostics.md already written against it.
DISPLAY = {"A. Conditional accuracy": "A. Descriptor error ($z$)"}


def _esc_title(t: str) -> str:
    """Family titles carry a leading 'A. ' etc. and no LaTeX-special chars,
    but they do contain hyphens that must not become en-dashes in a table."""
    return DISPLAY.get(t, t).replace("lookup-proof", "lookup\\nobreakdash-proof")


def _write(name: str, body: str, source: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    p = OUT / name
    p.write_text(f"% GENERATED by tools/make_paper_tables.py from {source}\n"
                 f"% Do not edit by hand -- edit the source or the generator.\n"
                 f"{body}\n")
    print(f"wrote {p}")


def _sci(x: float, sig: int = 2) -> str:
    """Math-mode scientific notation. `1.62e-04` typesets as literal text in a
    sentence; the macro is used in prose, so it has to arrive as math."""
    mant, exp = f"{x:.{sig}e}".split("e")
    return f"$%s\\times 10^{{%d}}$" % (mant, int(exp))


def preproc_macros() -> None:
    """Macros for the numbers Section 3 states about a clip.

    Note \\VoxelRate is the CLIP rate, not the burst-window rate. A clip is a
    288 ms span drawn at random inside a 600 ms window and the draw lands
    preferentially on the active part, so the two differ by about 2x. Every
    other number in the paper is computed on clips.
    """
    d = json.loads(Path("reports/preproc_stats.json").read_text())
    m = [f"\\newcommand{{\\FrameMs}}{{{d['frame_ms']:.0f}}}",
         f"\\newcommand{{\\WindowMs}}{{{d['window_ms']:.0f}}}",
         f"\\newcommand{{\\ClipMs}}{{{d['clip_ms']:.0f}}}",
         f"\\newcommand{{\\ClipFrames}}{{{d['clip_frames']}}}",
         f"\\newcommand{{\\ClipVoxels}}{{{d['clip_voxels']:,}}}",
         f"\\newcommand{{\\NWindows}}{{{d['n_windows']:,}}}",
         f"\\newcommand{{\\VoxelRate}}{{{_sci(d['clip_voxel_rate'])}}}",
         f"\\newcommand{{\\SpikesPerClip}}{{{d['mean_spikes_per_clip']:.0f}}}",
         f"\\newcommand{{\\NTrain}}{{{d['split_counts']['train']}}}",
         f"\\newcommand{{\\NVal}}{{{d['split_counts']['val']}}}",
         f"\\newcommand{{\\NTest}}{{{d['split_counts']['test']}}}"]
    _write("preproc_macros.tex", "\n".join(m), "reports/preproc_stats.json")


def eval_macros() -> None:
    """Macros for numbers the main text states about the evaluation itself.

    These move with the pinned protocol, so they are read from the artifacts
    rather than written into the prose. \\CeilingFactor in particular is a
    ratio of two oracle-code scores and would otherwise be a hand-computed
    number sitting in the abstract.
    """
    ours = json.loads((EB / "task_eval_pipeline.json").read_text())
    flat = json.loads((EB / "task_eval_maskgit_flat.json").read_text())
    o = ours["tasks"]["recon"]["arms"]["oracle"]
    f = flat["tasks"]["recon"]["arms"]["oracle"]
    m = [f"\\newcommand{{\\CeilingFactor}}{{{o['mean'] / f['mean']:.1f}}}",
         f"\\newcommand{{\\OracleOurs}}{{{o['mean']:.4f}}}",
         f"\\newcommand{{\\OracleFlat}}{{{f['mean']:.4f}}}",
         f"\\newcommand{{\\OracleOursSite}}{{{o['site_mean']:.4f}}}",
         f"\\newcommand{{\\OracleFlatSite}}{{{f['site_mean']:.4f}}}"]

    b = json.loads(Path("reports/eval_budget.json").read_text())

    # The manuscript says every number comes from one pinned protocol scored
    # identically for every arm. That is a claim about the runs, so it is
    # checked here rather than trusted: if the two batteries ever diverge
    # again, the macros refuse to render and the sentence cannot survive a
    # rebuild. (They did diverge once -- 12 and 8 unshuffled batches, which is
    # a prefix of the split rather than a sample of it, and reached 6 and 4 of
    # the recordings.)
    budgets = b["budgets"]
    spans = {n: (c["batches"], c["clips"], c["recordings"])
             for n, c in budgets.items()}
    if len(set(spans.values())) != 1:
        raise SystemExit(
            "the evaluation batteries do not share a protocol: "
            + "; ".join(f"{n} = {v[0]} batches, {v[1]} clips, {v[2]} recordings"
                        for n, v in spans.items())
            + " -- Section 5's single-protocol sentence would be false")
    if not b.get("all_recordings_covered"):
        raise SystemExit("the pinned protocol does not cover every recording")

    m += [f"\\newcommand{{\\NTestClips}}{{{b['test_clips_available']}}}"]
    for name, tag in (("task_axis", "Task"), ("diagnostics", "Diag")):
        cfg = budgets[name]
        m += [f"\\newcommand{{\\N{tag}Batches}}{{{cfg['batches']}}}",
              f"\\newcommand{{\\N{tag}Clips}}{{{cfg['clips']}}}",
              f"\\newcommand{{\\N{tag}Recordings}}{{{cfg['recordings']}}}",
              f"\\newcommand{{\\N{tag}Seed}}{{{cfg['seed']}}}",
              f"\\newcommand{{\\N{tag}MC}}{{{cfg['mc'] or 1}}}"]
    _write("eval_macros.tex", "\n".join(m),
           "reports/external_baselines/task_eval_*.json, reports/eval_budget.json")


def data_provenance() -> None:
    """The 31 recordings, their source, and what the archive does not say."""
    d = json.loads(Path("reports/data_provenance.json").read_text())
    rows = []
    for r in d["used"]:
        prep = "organoid" if r["dandiset"] == "000732" else "slice"
        rows.append(
            f"{r['assay_idx']} & {_esc(r['assay_name'].replace('_ecephys', ''))} & "
            f"{r['dandiset']} & {prep} & {_esc(r.get('subject_id', '--'))} & "
            f"{_esc(r.get('age', '--'))} & {_esc(r.get('sex', '--'))} & "
            f"{r.get('n_routed_channels', 0)} & {r.get('duration_s', 0):.0f} & "
            f"\\texttt{{{r.get('electrode_config_md5', '--')}}} \\\\")
    body = ("\\begin{tabular}{r l l l l l c r r l}\n\\toprule\n"
            "idx & recording & dandiset & prep. & subject & age & sex & "
            "chan. & dur.\\,(s) & routing \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("data_provenance.tex", body, "reports/data_provenance.json")

    # The counts the main text quotes, so §3 does not hand-type them either.
    by = d["by_preparation"]
    macros = [f"\\newcommand{{\\NAssays}}{{{d['n_used']}}}"]
    for k, v in by.items():
        tag = "Organoid" if "organoid" in k else "Slice"
        macros.append(f"\\newcommand{{\\N{tag}Assays}}{{{v}}}")
    cfgs = {r["dandiset"]: set() for r in d["used"]}
    for r in d["used"]:
        cfgs[r["dandiset"]].add(r.get("electrode_config_md5"))
    macros.append(f"\\newcommand{{\\NOrganoidRoutings}}{{{len(cfgs['000732'])}}}")
    macros.append(f"\\newcommand{{\\NSliceRoutings}}{{{len(cfgs['001132'])}}}")
    ch = [r["n_routed_channels"] for r in d["used"]]
    macros.append(f"\\newcommand{{\\ChanMin}}{{{min(ch)}}}")
    macros.append(f"\\newcommand{{\\ChanMax}}{{{max(ch)}}}")
    _write("data_macros.tex", "\n".join(macros), "reports/data_provenance.json")


def scalability() -> None:
    """Where each arm keeps its capacity: shared weights, or a per-assay table."""
    c = json.loads((EB / "param_census.json").read_text())["arms"]
    rows = []
    for key, label in ARMS:
        v = c.get(key)
        if v is None:
            continue
        fitted = v.get("fitted", v["shared"])
        rows.append(f"{label} & {fitted:,} & {v.get('shared_maps', 0):,} & "
                    f"\\textbf{{{v['per_assay']:,}}} & "
                    f"{v['per_assay'] * 1000:,} \\\\")
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "arm & fitted (shared) & shared maps & per recording & "
            "at 1000 recordings \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t1_scalability.tex", body,
           "reports/external_baselines/param_census.json")


def generation() -> None:
    """The four generation families at full context, each with its own null.

    The bracketed value is that same arm's `random`-context score, so a cell
    whose value and null are close is not using its conditioning. Without it a
    reader cannot tell conditioning from an arm's default behaviour, which is
    exactly what the lookup arms do once their per-assay map is withheld.

    Source is `generation_families.json`, emitted by
    `external_baselines.diagnose_table --emit-families`. NOT comparison.json:
    that file's `per_clip` block holds nine per-clip statistics over seven
    pipeline variants, excludes both convolutional arms, and its
    stat_error_clean median is the conditioning-gain median rather than the
    glob+full value the paper quotes -- rendering from it would silently
    disagree with diagnostics.md.
    """
    src = EB / "generation_families.json"
    if not src.exists():
        raise SystemExit(
            f"{src} missing. Generate it with:\n"
            f"  python -m MAGVIT_project.external_baselines.diagnose_table "
            f"--emit-families\n"
            f"The four families exist only inside diagnose_table.py; do not "
            f"transcribe them from diagnostics.md.")
    d = json.loads(src.read_text())
    FULL, NULL = "global_full_local", "random"
    # Keys as diagnose_table's MODELS labels them, in the order the paper
    # argues. The dagger and the _ref_ marks travel with the label so a caption
    # cannot forget them.
    LABEL = [("Ours (4C+soft)", "Ours"),
             ("MaskGIT-flat", "MaskGIT-flat"),
             ("3D U-Net (det.)\u2020", "3D U-Net$^\\dagger$"),
             ("3D CVAE", "3D CVAE"),
             ("Dich. Gaussian", "\\emph{ref} DG"),
             ("Coupled GLM", "\\emph{ref} GLM")]

    rows = []
    for title, blk in d["families"].items():
        arrow = "$\\downarrow$" if blk["better"] == "low" else "$\\uparrow$"
        cells = []
        for raw, _lbl in LABEL:
            v = blk["arms"].get(raw)
            cells.append("--" if v is None else
                         f"{v[FULL]:.4f} \\emph{{[{v[NULL]:.3f}]}}")
        rows.append(f"{_esc_title(title)} {arrow} & " + " & ".join(cells)
                    + " \\\\")

    header = " & ".join(lbl for _, lbl in LABEL)
    body = ("\\begin{tabular}{l r r r r r r}\n\\toprule\n"
            f"family & {header} \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t3_generation_families.tex", body, str(src))


def task_completion() -> None:
    """Site-level and voxel-level AP on the four completion tasks.

    Two blocks of one table because they answer different questions -- which
    ELECTRODE fires, and whether the FRAME is right too -- and our result
    differs sharply between them. Nothing is bolded: 20 of the 32 paired tests
    go to another arm, so a bolded scoreboard would imply a competition this
    work does not win. Cells carry the paired-test verdict instead.

    Read WITHIN a column only. The ROI fraction differs by task
    (1.00 / 0.60 / 0.41 / 0.33), so the columns have different base rates.
    `recon` is free generation at zero context, not a fourth completion task.
    """
    src = EB / "cross_model_tests.json"
    d = json.loads(src.read_text())
    # The null is the point of the table, so it is a row and not a footnote:
    # `marginal` is the clip's own recording's per-site firing rate measured on
    # that recording's TRAIN clips and held constant in time -- no model, no
    # completion, no clip-specific information at all. Every learned arm loses
    # to it. `marginal_xa` withholds the clip's own recording, and the distance
    # between the two rows is how much of the first is memorisation.
    nulls = json.loads((EB / "task_eval_nulls.json").read_text())["tasks"]
    TASKS = ["recon", "causal", "noncausal", "spatial"]
    ARMLBL = {"MaskGIT-flat": "MaskGIT-flat",
              "3D U-Net (det.)": "3D U-Net$^\\dagger$",
              "3D CVAE": "3D CVAE"}
    MARK = {"pipeline": "$^{\\ast}$", "arm": "", "ns": "$^{\\circ}$"}

    ours, per_arm = {}, {}
    for r in d["rows"]:
        if r["arm"] not in ARMLBL:
            continue
        ours[(r["family"], r["task"])] = r["pipeline"]
        per_arm[(r["family"], r["task"], r["arm"])] = r

    blocks = []
    for fam, famlbl in (("site AP", "Site AP $\\uparrow$: which electrode"),
                        ("voxel AP",
                         "Voxel AP $\\uparrow$: which electrode \\emph{and} frame")):
        blocks.append(f"\\multicolumn{{5}}{{l}}{{\\textit{{{famlbl}}}}} \\\\")
        blocks.append("Ours & " + " & ".join(
            f"{ours[(fam, t)]:.4f}" for t in TASKS) + " \\\\")
        for arm, lbl in ARMLBL.items():
            cells = []
            for t in TASKS:
                r = per_arm.get((fam, t, arm))
                cells.append("--" if r is None
                             else f"{r['arm_value']:.4f}{MARK[r['verdict']]}")
            blocks.append(f"{lbl} & " + " & ".join(cells) + " \\\\")
        fld = "site_ap" if fam == "site AP" else "ap"
        for nk, nlbl in (("marginal", "\\emph{null} recording site map, seen"),
                         ("marginal_xa",
                          "\\emph{null} recording site map, unseen")):
            blocks.append(f"{nlbl} & " + " & ".join(
                f"{nulls[t]['arms'][nk][fld]:.4f}" for t in TASKS) + " \\\\")
        blocks.append("\\midrule")
    blocks.pop()

    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "arm & free gen.\\ (0) & causal (1) & noncausal (2) & spatial (3)"
            " \\\\\n\\midrule\n" + "\n".join(blocks)
            + "\n\\bottomrule\n\\end{tabular}")
    _write("t2_task_completion.tex", body, str(src))


def stage_prior_ladder() -> None:
    """Stage 4A motif prior against the four-rung null ladder.

    The strongest null is `assay_position` -- the empirical distribution of
    codes at that grid position within that recording. Beating `uniform` is
    worth nothing; the ladder exists so the reported margin is against the
    hardest available lookup, and `null_strongest_level` records which that is.

    Median rank, never mean: the distribution has a long tail and the mean
    (44.65) misrepresents the median (9.0).
    """
    src = Path("reports/evaluation_report_prior_4A_V961.json")
    d = json.loads(src.read_text())
    assert d["null_strongest_level"] == "assay_position", d["null_strongest_level"]
    rows = []
    for pre, lbl in (("null_uniform_z1", "uniform"),
                     ("null_global_z1", "global marginal"),
                     ("null_assay_z1", "per-recording marginal"),
                     ("null_assay_position_z1",
                      "per-recording $\\times$ position")):
        rows.append(f"{lbl} & {d[pre+'_acc']:.4f} & {d[pre+'_top5_acc']:.4f} & "
                    f"{d[pre+'_median_rank']:.0f} & {d[pre+'_mrr']:.4f} & "
                    f"{d[pre+'_ce']:.4f} \\\\")
    rows.append("\\midrule")
    rows.append(f"\\textbf{{motif prior (ours)}} & "
                f"\\textbf{{{d['flat_acc']:.4f}}} & "
                f"\\textbf{{{d['flat_top5_acc']:.4f}}} & "
                f"\\textbf{{{d['flat_median_rank']:.0f}}} & "
                f"\\textbf{{{d['flat_mrr']:.4f}}} & "
                f"\\textbf{{{d['loss_flat']:.4f}}} \\\\")
    body = ("\\begin{tabular}{l r r r r r}\n\\toprule\n"
            "predictor & top-1 $\\uparrow$ & top-5 $\\uparrow$ & "
            "median rank $\\downarrow$ & MRR $\\uparrow$ & "
            "CE (nats) $\\downarrow$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t4c_prior_nulls.tex", body, str(src))


def motif_reuse() -> None:
    """Is the alphabet shared across recordings? The thesis's own table.

    Only the RAREFIED overlap is rendered. The raw Jaccard in the same JSON
    tracks sampling effort at r = +0.96 and is explicitly marked unquotable by
    the analysis that produced it; putting it in a paper table would undo that.
    """
    src = Path("reports/analysis_motif_reuse.json")
    d = json.loads(src.read_text())
    e, jr = d["entropy"], d["jaccard_rarefied"]
    rows = [
        f"alphabet entries in use & {d['vocab_global']} of {d['V']} \\\\",
        f"used by $\\geq 5$ recordings, rarefied & "
        f"{d['shared_core']['used_by_ge_k_rarefied']['5']:.0f} \\\\",
        "\\midrule",
        f"$H(\\mathrm{{code}})$ & {e['H_code_mm']:.4f} nats \\\\",
        f"$H(\\mathrm{{code}} \\mid \\mathrm{{recording}})$ & "
        f"{e['H_code_given_recording_mm']:.4f} nats \\\\",
        f"\\textbf{{retained fraction}} & "
        f"\\textbf{{{e['reuse_ratio_mm']:.4f}}} \\\\",
        "\\midrule",
        f"rarefied overlap, within organoid & "
        f"{jr['mean_within_organoid']:.4f} \\\\",
        f"rarefied overlap, within slice & {jr['mean_within_slice']:.4f} \\\\",
        f"rarefied overlap, across preparation types & "
        f"{jr['mean_cross_prep']:.4f} \\\\",
        f"\\emph{{null}} label-shuffled & {jr['null_mean']:.4f} "
        f"$\\pm$ {jr['null_sd']:.4f} \\\\",
    ]
    body = ("\\begin{tabular}{l r}\n\\toprule\n"
            "quantity & value \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t5_motif_reuse.tex", body, str(src))


def stage_contributions() -> None:
    """Stage 3 and the ladder: the two rows of T4 that are fully derivable."""
    s3 = json.loads(Path("reports/analysis_stage3_lct.json").read_text())
    last = s3[-1]
    rows = []
    for arm, label in (("lct", "\\texttt{lct} only"),
                       ("gct", "\\texttt{gct} only"),
                       ("both", "both")):
        v = last[arm]
        rows.append(f"{label} & {v['dnll_flat']:.4f} & {v['dnll_tex']:.4f} & "
                    f"{v['r2_tcent']:.4f} & {v['r2_tmarg']:.4f} \\\\")
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "conditioning & $\\Delta$NLL flat $\\uparrow$ & "
            "$\\Delta$NLL texton $\\uparrow$ & $R^2$ $t$-centroid $\\uparrow$ & "
            "$R^2$ $t$-marginal $\\uparrow$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t4b_stage3_lct.tex", body, "reports/analysis_stage3_lct.json")

    lad = json.loads(Path("reports/ablation_ladder_decode_depth.json").read_text())
    lv, inc = lad["levels"], lad["increments"]
    order = [("z1", "$z_1$", None),
             ("z1+z2", "$z_1{+}z_2$", "z1 -> z1+z2"),
             ("z1+z2+z3", "$z_1{+}z_2{+}z_3$", "z1+z2 -> z1+z2+z3")]
    rows = []
    for key, label, ikey in order:
        gain = "--"
        if ikey:
            g = inc[ikey]
            gain = (f"\\textbf{{$+${g['mean_delta']:.4f}}} "
                    f"({g['win_frac']*100:.0f}\\% of clips)")
        rows.append(f"{label} & {lv[key]['mean']:.4f} & {gain} \\\\")
    body = ("\\begin{tabular}{l r l}\n\\toprule\n"
            "decode depth & AP $\\uparrow$ & gain over previous \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t4a_ladder_depth.tex", body,
           "reports/ablation_ladder_decode_depth.json")


# ---------------------------------------------------------------------------
# Appendix tables. Same rule: read the artifact, never retype it.
# ---------------------------------------------------------------------------

def app_patch_sweep() -> None:
    """The full patch-size sweep cut from the main text.

    The point of showing all of it is that the two columns disagree: capture
    rises monotonically as the patch shrinks while the blank fraction rises
    with it, and the prior is what pays for the blanks.
    """
    src = Path("reports/ablation_patch_size.json")
    d = json.loads(src.read_text())
    rows = []
    for r in sorted(d["rows"], key=lambda r: -r["voxels_per_patch"]):
        t, h, w = r["patch"]
        lab = f"$({t},{h},{w})$"
        if r["is_shipped"]:
            lab = "\\textbf{" + lab + "} (shipped)"
        rows.append(f"{lab} & {r['voxels_per_patch']} & {r['n_tokens']} & "
                    f"{r['blank_frac']*100:.1f} & {r['active_tokens']:.1f} & "
                    f"{r['spikes_per_active']:.2f} & {r['capture_k32']:.4f} \\\\")
    body = ("\\begin{tabular}{l r r r r r r}\n\\toprule\n"
            "patch $(T,H,W)$ & voxels & tokens & blank \\% & active tok. & "
            "spikes/active & capture$_{K=32}$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("a_patch_sweep.tex", body, str(src))


def app_texton_basis() -> None:
    """Which basis the Stage 3 textons are clustered on, and how many.

    Rendered as delta-NLL against that basis's own marginal, so the six cells
    are comparable despite having different base entropies -- which are given
    in the row below the table by the caller.
    """
    src = Path("reports/analysis_stage1c_texton_basis.json")
    last = json.loads(src.read_text())["log"][-1]
    bases = [("z1_32", "$z_1$, 32"), ("z1_128", "$z_1$, 128"),
             ("z12_32", "$z_1{+}z_2$, 32"), ("z12_128", "$z_1{+}z_2$, 128"),
             ("flat_32", "flat, 32"), ("flat_128", "flat, 128")]
    rows = []
    for key, lab in bases:
        cells = " & ".join(f"{last['arms'][a][key]['dnll']:.4f}"
                           for a in ("lct", "gct", "both"))
        rows.append(f"{lab} & {last['base'][key]:.4f} & {cells} \\\\")
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "basis, \\#textons & base NLL & $\\Delta$\\texttt{lct} & "
            "$\\Delta$\\texttt{gct} & $\\Delta$both \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("a_texton_basis.tex", body, str(src))


def app_seed_spread() -> None:
    """The adaptation stage across four seeds, including the shipped one.

    Two metrics, and they disagree, which is the point of showing both. Val MRR
    is what selected the shipped checkpoint; deployment MRR on the test split is
    what it is worth. The shipped run is the WORST of the four on deployment.
    Swapping in the best-deploying seed after the fact would be selecting on
    test, so the val-selected checkpoint ships and the table says so.
    """
    src = Path("reports/stage4c_seed_spread.json")
    dep_src = Path("reports/stage4c_seed_deployment.json")
    d = json.loads(src.read_text())
    dep = json.loads(dep_src.read_text())["deployment_mrr"]
    rows = []
    for key in ("shipped", "101", "202", "303"):
        v = d[key]
        lab = "\\textbf{shipped}" if key == "shipped" else f"seed {key}"
        dk = "shipped" if key == "shipped" else f"seed{key}"
        rows.append(f"{lab} & {v['best_epoch']} & {v['epochs_run']} & "
                    f"{v['best_mrr']:.5f} & {dep[dk]:.5f} \\\\")
    dd = json.loads(dep_src.read_text())
    sm = d["_summary"]
    rows += ["\\midrule",
             f"mean $\\pm$ sd & & & {sm['mean_best_val_mrr']:.5f} "
             f"$\\pm$ {sm['sd_best_val_mrr']:.5f} & "
             f"{dd['mean']:.5f} $\\pm$ {dd['sd']:.5f} \\\\",
             "\\midrule",
             f"\\emph{{ref}} no adaptation, soft field & & & & "
             f"{dd['ref_4a_soft']:.5f} \\\\",
             f"\\emph{{ref}} no adaptation, hard map & & & & "
             f"{dd['ref_4a_hard']:.5f} \\\\",
             f"\\emph{{ref}} oracle activity map & & & & "
             f"{dd['oracle']:.5f} \\\\"]
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "run & best epoch & epochs & val MRR & deployment MRR \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n"
            "\\end{tabular}")
    _write("a_seed_spread.tex", body, f"{src}, {dep_src}")


def app_generation_ladders() -> None:
    """All five conditioning rungs for all four generation families.

    The collapsed main-text table keeps only the first and last rung; the
    monotonicity between them is the evidence that conditioning is used, so
    the full ladder belongs somewhere.
    """
    src = EB / "generation_families.json"
    d = json.loads(src.read_text())
    rungs = d["rungs"]
    head = " & ".join(_esc(r.replace("_", " ")) for r in rungs)
    blocks = []
    for fam, blk in d["families"].items():
        arrow = "$\\downarrow$" if blk["better"] == "low" else "$\\uparrow$"
        blocks.append("\\multicolumn{6}{l}{\\textbf{" + _esc_title(_esc(fam))
                      + "} " + arrow + "} \\\\")
        for arm, vals in blk["arms"].items():
            cells = " & ".join(f"{vals[r]:.4f}" for r in rungs)
            blocks.append(f"\\quad {_esc(arm)} & {cells} \\\\")
        blocks.append("\\midrule")
    blocks = blocks[:-1]
    body = ("\\begin{tabular}{l r r r r r}\n\\toprule\n"
            f"arm & {head} \\\\\n\\midrule\n"
            + "\n".join(blocks) + "\n\\bottomrule\n\\end{tabular}")
    _write("a_generation_ladders.tex", body, str(src))


def app_withheld_map() -> None:
    """What the two lookup arms are worth once their per-recording map is gone.

    Adherence is `lct_r_mean_vs_used` and the gap is `within_assay_gap`, both
    at the full-context rung, exactly as the diagnostics block reads them.
    """
    rows = []
    for key, lab in (("dg", "Dich.\\ Gaussian"), ("glm", "Coupled GLM")):
        with_map = json.loads((EB / f"diagnose_{key}.json").read_text())
        without = json.loads((EB / f"diagnose_{key}_NOMAP.json").read_text())
        a = with_map["context_and_space"]["regimes"]["global_full_local"]
        b = without["context_and_space"]["regimes"]["global_full_local"]
        rows.append(f"{lab} & {a['within_assay_gap']:+.4f} & "
                    f"{b['within_assay_gap']:+.4f} & "
                    f"{a['lct_r_mean_vs_used']:+.4f} & "
                    f"{b['lct_r_mean_vs_used']:+.4f} & "
                    f"{a['map_pearson_r']:.4f} & {b['map_pearson_r']:.4f} "
                    f"\\\\")
    body = ("\\begin{tabular}{l r r r r r r}\n\\toprule\n"
            "\\emph{ref} arm & \\multicolumn{2}{c}{within-recording gap} & "
            "\\multicolumn{2}{c}{adherence} & "
            "\\multicolumn{2}{c}{map $r$} \\\\\n"
            "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\n"
            " & with & without & with & without & with & without "
            "\\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("a_withheld_map.tex", body, "reports/external_baselines/diagnose_{dg,glm}[_NOMAP].json")


def _lr(x: float) -> str:
    """Learning rates span 1e-3 to 3e-5, so a fixed number of decimals either
    truncates one end or pads the other. Scientific notation reads the same at
    both."""
    return _sci(float(x), 0).replace(".0", "") if float(x) else "0"


def _term(key: str) -> str:
    """Render a loss-coefficient name as mathematics, not as an identifier.

    `lambda_ctx` in a caption is a variable name leaking out of the code; the
    paper's convention is that a coefficient is typeset as the symbol it is.
    """
    if key.startswith("lambda_"):
        sub = key[len("lambda_"):].replace("_", "\\,")
        return f"$\\lambda_{{\\mathrm{{{sub}}}}}$"
    return _esc(key.replace("_", " "))


def _val(v) -> str:
    if isinstance(v, bool):
        return "on" if v else "off"
    if isinstance(v, (list, tuple)):
        return "$(" + ", ".join(str(x) for x in v) + ")$"
    return _esc(str(v))


def app_pooled_marginals() -> None:
    """Per-clip relative error on the pooled summary statistics.

    Limitations states the direction of this result rather than the values, so
    the values have to live somewhere a reader can check them. The reference
    column is ours; every other column is that arm's median with the paired
    difference against us and its BH-corrected q.

    These come from `comparison.json`, the generation-regime sample sets, which
    is a different instrument from the four families in
    Table~\\ref{tab:generation}: it scores four independent draws per clip
    rather than one, and it scores pooled statistics rather than adjacency.
    """
    d = json.loads((EB / "comparison.json").read_text())
    pc = d["per_clip"]
    ref = d["reference"]
    rows_want = [("rel_rate", "firing rate"),
                 ("rel_persist4", "$4$-frame persistence"),
                 ("rel_avalanche_mean", "mean avalanche size"),
                 ("ks_isi", "ISI distribution (KS)"),
                 ("ks_avalanche", "avalanche size (KS)"),
                 ("stat_error_clean", "aggregate")]
    # The matched generative peer, then the two lookup references. The four
    # other pipeline variants in this file are internal ablations and belong in
    # the stage appendix, not in a comparison against other people's methods.
    want = ["MaskGIT-flat", "DG (Macke'09)", "GLM (Pillow'08)"]
    arms = [a for a in want if a in pc[rows_want[0][0]]]
    if not arms:
        raise SystemExit(f"comparison.json has none of {want}; it holds "
                         f"{sorted(pc[rows_want[0][0]])}")
    head = " & ".join(f"\\multicolumn{{2}}{{c}}{{{_esc(a)}}}" for a in arms)
    rows = []
    for key, lab in rows_want:
        if key not in pc:
            continue
        cells = [f"{pc[key][ref]['median']:.4f}"]
        for a in arms:
            e = pc[key].get(a, {})
            q = e.get("q")
            cells += [f"{e.get('median', float('nan')):.4f}",
                      "--" if q is None else _sci(q, 1)]
        rows.append(f"{lab} & " + " & ".join(cells) + " \\\\")
    body = ("\\begin{tabular}{l r " + "r r " * len(arms) + "}\n\\toprule\n"
            f"statistic & {_esc(ref)} & {head} \\\\\n"
            + "".join(f"\\cmidrule(lr){{{3 + 2 * i}-{4 + 2 * i}}}"
                      for i in range(len(arms))) + "\n"
            " & median & " + " & ".join(["median & $q$"] * len(arms))
            + " \\\\\n\\midrule\n" + "\n".join(rows)
            + "\n\\bottomrule\n\\end{tabular}")
    _write("a_pooled_marginals.tex", body,
           "reports/external_baselines/comparison.json")


# The supervision target and the frozen hand-off are properties of the design,
# not of a run, so they are named here; the stage list, what each stage trains
# and how it is selected all come from the extractor, so a renamed or dropped
# stage breaks this table instead of leaving a stale row in the paper.
_STAGE_ROLE = {
    "1":  ("the recording's running union of active sites",
           "frozen code-to-support mapper"),
    "2A": ("the clip itself, reconstructed through the quantiser",
           "frozen motif alphabet, $V=961$"),
    "3":  ("the clip's texton usage histogram",
           "frozen nine-scalar-to-code mapper"),
    "4A": ("true motifs, given the \\emph{true} activity field",
           "motif generator"),
    "4B": ("the true activity field and its total count",
           "activity generator"),
    "4C": ("true motifs, given the activity field 4B \\emph{emits}",
           "the prior used at inference"),
}


def stage_chronology() -> None:
    """The four-stage sequence, one row per stage.

    Section 4.5 leans on this table instead of narrating the chronology, so it
    has to be complete: a stage silently missing here would read as a stage the
    paper does not have.
    """
    d = json.loads(Path("reports/hyperparameters.json").read_text())
    missing = [s["stage"] for s in d["stages"] if s["stage"] not in _STAGE_ROLE]
    if missing:
        raise SystemExit(f"stage_chronology: no role text for {missing}; the "
                         "pipeline gained a stage and this table would omit it")
    rows, sel = [], []
    for st in d["stages"]:
        target, out = _STAGE_ROLE[st["stage"]]
        rows.append(f"{st['stage']} & {_esc(st['trained'])} & {target} & "
                    f"{out} \\\\")
        sel.append(f"{st['stage']} on {_esc(st['select_on'])}")
    # Four prose columns at 5.5in is already tight; the selection metric moves
    # to a footnote so the remaining columns get enough width not to wrap into
    # a table twice as tall as it needs to be.
    rag = ">{\\raggedright\\arraybackslash}"
    body = ("\\begin{tabular}{@{}l " + rag + "p{0.24\\textwidth} " + rag
            + "p{0.30\\textwidth} " + rag + "p{0.26\\textwidth}@{}}\n"
            "\\toprule\n"
            "stage & what it trains & supervision target & "
            "frozen output used later \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\n"
            "\\vspace{0.3em}\n\n"
            "{\\footnotesize Checkpoint selection: "
            + "; ".join(sel) + ".}")
    _write("t1_stages.tex", body, "reports/hyperparameters.json")


def app_cvae_collapse() -> None:
    """What was done to stop the CVAE's latent collapsing, and what happened.

    A reviewer's first thought on reading "the latent collapses" is that the
    arm was under-tuned so that it would. The answer is the list of standard
    anti-collapse measures, all of which were applied, and two independent fits
    that collapse anyway -- so the settings and the outcome are both read from
    the fit reports rather than asserted in a sentence.
    """
    rows, cfg = [], None
    for name, label in (("cvae3d", "shipped"),
                        ("cvae3d_nopos", "no positional embedding")):
        d = json.loads(Path(f"ckpts/external_baselines/{name}.fit.json").read_text())
        cfg = cfg or d["config"]
        k = d["val_kl_per_dim_per_epoch"]
        rows.append(f"{label} & {d['epochs_run']} & {max(k):.4f} & "
                    f"{d['final_val_kl_per_dim']:.4f} & "
                    f"{'yes' if d['latent_collapsed'] else 'no'} \\\\")
    note = (
        "Both fits carry the standard anti-collapse measures: a "
        "\\emph{conditional} prior $p(z \\mid c)$ in place of "
        "$\\mathcal{N}(0, I)$; the KL down-weighted to $\\beta = "
        f"{cfg['beta']}$; KL warm-up over the first "
        f"{cfg['kl_warmup_frac'] * 100:.0f}\\% of training; free bits at "
        f"{cfg['free_bits']} applied \\emph{{per channel}}, which is where "
        "collapse happens; the KL charged only on the latent cells the hole "
        "touches, so the latent is not taxed for what the skip connections "
        "already carry; and the posterior log-variance initialised at "
        f"${cfg['post_logvar_init']}$. The latent is a {cfg['z_ch']}-channel "
        "grid and not a global vector, so it can say \\emph{where} the extra "
        "spikes go.")
    body = ("\\begin{tabular}{@{}l r r r l@{}}\n\\toprule\n"
            "fit & epochs & peak val KL/dim & final val KL/dim & collapsed "
            "\\\\\n\\midrule\n" + "\n".join(rows)
            + "\n\\bottomrule\n\\end{tabular}\n\n\\vspace{0.4em}\n\n"
            "\\begin{minipage}{\\textwidth}\\footnotesize\n" + note
            + "\n\\end{minipage}")
    _write("a_cvae_collapse.tex", body,
           "ckpts/external_baselines/cvae3d*.fit.json")


def app_objectives() -> None:
    """Every loss term of every stage, with its coefficient and its job.

    The Method names these terms and says what each constrains; without this
    table that pointer has nowhere to land. Coefficients come from
    `tools/extract_hparams.py`, which reads them out of the source -- including
    two that no obvious source line reports correctly, Stage 2A's context
    weight (rebound at runtime) and Stage 4B's lambdas (one of two config
    dicts). The descriptions are prose and live in that generator.
    """
    d = json.loads(Path("reports/hyperparameters.json").read_text())
    rows = []
    for obj in d["objectives"]:
        rows.append(f"\\multicolumn{{3}}{{l}}{{\\textbf{{Stage {_esc(obj['stage'])}}}"
                    f"\\quad ${obj['symbol']}$}} \\\\[0.15em]")
        for t in obj["terms"]:
            rows.append(f"\\quad {_esc(t['term'])} & {_esc(_val(t['coeff']))} & "
                        f"{_esc(t['constrains'])} \\\\")
        rows.append("\\addlinespace")
    off = "; ".join(f"{_esc(x['where'])}, {_esc(x['what'])} ({_esc(x['why'])})"
                    for x in d["disabled"])
    body = (
        "\\begin{tabular}{@{}>{\\raggedright\\arraybackslash}p{0.24\\textwidth} "
        "l >{\\raggedright\\arraybackslash}p{0.44\\textwidth}@{}}\n\\toprule\n"
        "term & coefficient & what it constrains \\\\\n\\midrule\n"
        + "\n".join(rows[:-1])
        + "\n\\bottomrule\n\\end{tabular}\n\n\\vspace{0.4em}\n\n"
        "\\begin{minipage}{\\textwidth}\\footnotesize\n"
        "Coefficients are constant unless noted; the ramps and curricula are in "
        "Appendix~\\ref{app:training}. Present in the code and inactive in the "
        f"shipped configuration: {off}.\n\\end{{minipage}}")
    _write("a_objectives.tex", body, "reports/hyperparameters.json")


def app_hyperparameters() -> None:
    """One row per shipped stage, from the source rather than from prose.

    The loss coefficients are a per-stage list rather than columns: the stages
    optimise different objectives, so a shared column set would be mostly empty
    and would imply the terms are comparable across rows.
    """
    d = json.loads(Path("reports/hyperparameters.json").read_text())
    rows = []
    for st in d["stages"]:
        clip = "--" if st["grad_clip"] is None else f"{st['grad_clip']:.1f}"
        sched = st["scheduler"]
        if "eta_min" in st:
            sched = f"{sched} to {_lr(st['eta_min'])}"
        warm = "--" if not st["warmup_epochs"] else str(st["warmup_epochs"])
        rows.append(
            f"{st['stage']} & {_esc(st['what'])} & {_lr(st['lr'])} & "
            f"{_lr(st['weight_decay'])} & {sched} & {warm} & "
            f"{st['epochs']} & {clip} & {st['early_stop_patience']} & "
            f"{_esc(st['select_on'])} \\\\")
    terms = []
    for st in d["stages"]:
        kv = ", ".join(f"{_term(k)} {_val(v)}" for k, v in st["loss_terms"].items())
        terms.append(f"\\textbf{{{st['stage']}}} {kv}")
    sh = d["shared"]
    # The \resizebox belongs HERE, around the tabular alone. Wrapping the whole
    # file scales the note too, and worse, an LR box lays the tabular and the
    # minipage out side by side: the note rendered as a squeezed right-hand
    # column at about four points instead of as a note under the table.
    body = (
        "\\resizebox{\\textwidth}{!}{%\n"
        "\\begin{tabular}{l l r r l r r r r l}\n\\toprule\n"
        "stage & what & lr & wd & schedule & warm & ep. & clip & pat. & "
        "selected on \\\\\n\\midrule\n" + "\n".join(rows)
        + "\n\\bottomrule\n\\end{tabular}}\n\n\\vspace{0.6em}\n\n"
        "\\begin{minipage}{\\textwidth}\\footnotesize\n"
        f"Shared across every stage: batch size {sh['batch_size']} with "
        f"{sh['grad_accum_steps']} accumulation steps, i.e.\\ an effective batch "
        f"of {sh['effective_batch']}; {_esc(sh['precision'])}; dropout "
        f"{sh['prior_dropout']} in both priors; seed {sh['seed']}. Stages run in "
        "sequence and every earlier stage is frozen thereafter.\\\\[0.3em]\n"
        "Per-stage settings. " + "; ".join(terms) + ".\n\\end{minipage}")
    _write("a_hyperparameters.tex", body, "reports/hyperparameters.json")


def main() -> int:
    preproc_macros()
    eval_macros()
    data_provenance()
    stage_chronology()
    scalability()
    task_completion()
    generation()
    motif_reuse()
    stage_contributions()
    stage_prior_ladder()
    app_patch_sweep()
    app_texton_basis()
    app_seed_spread()
    app_generation_ladders()
    app_withheld_map()
    app_cvae_collapse()
    app_objectives()
    app_hyperparameters()
    app_pooled_marginals()
    print("\nRemaining tables are trims of rendered blocks in "
          "reports/external_baselines/diagnostics.md; port them here as they "
          "are finalised so nothing in the paper is hand-typed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
