#!/usr/bin/env python3
"""Render the paper's tables to LaTeX from the committed report artifacts.

Same rule as `external_baselines/diagnose_table.py`: no number is typed into
prose or into a `.tex` file by hand. Every cell here is read from a JSON file in
`reports/`, so a table cannot drift from the run that produced it, and a
reviewer's question about any cell resolves to a file path.

    python tools/make_paper_tables.py

Writes paper/tables/*.tex, each a bare `tabular` meant to be `\\input` inside a
float, so the caption and label live with the surrounding text.
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("paper/tables")
EB = Path("reports/external_baselines")

# Display names, in the order the paper argues. Ours first, then the learned
# peer, then the two conv arms, then the lookups -- which are ceilings and are
# marked as such rather than being allowed to win a bolded comparison.
ARMS = [("pipeline", "Ours"), ("maskgit_flat", "MaskGIT-flat"),
        ("unet3d", "3D U-Net$^\\dagger$"), ("cvae3d", "3D CVAE"),
        ("dg", "\\emph{ref} Dich.\\ Gaussian"), ("glm", "\\emph{ref} Coupled GLM")]


def _esc(s: str) -> str:
    return str(s).replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")


def _esc_title(t: str) -> str:
    """Family titles carry a leading 'A. ' etc. and no LaTeX-special chars,
    but they do contain hyphens that must not become en-dashes in a table."""
    return t.replace("lookup-proof", "lookup\\nobreakdash-proof")


def _write(name: str, body: str, source: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    p = OUT / name
    p.write_text(f"% GENERATED by tools/make_paper_tables.py from {source}\n"
                 f"% Do not edit by hand -- edit the source or the generator.\n"
                 f"{body}\n")
    print(f"wrote {p}")


def _sci(x: float, sig: int = 2) -> str:
    """Math-mode scientific notation. `1.62e-04` typesets as literal text in a
    sentence; the macro is used in prose, so it has to arrive as math."""
    mant, exp = f"{x:.{sig}e}".split("e")
    return f"$%s\\times 10^{{%d}}$" % (mant, int(exp))


def preproc_macros() -> None:
    """Macros for the numbers Section 3 states about a clip.

    Note \\VoxelRate is the CLIP rate, not the burst-window rate. A clip is a
    288 ms span drawn at random inside a 600 ms window and the draw lands
    preferentially on the active part, so the two differ by about 2x. Every
    other number in the paper is computed on clips.
    """
    d = json.loads(Path("reports/preproc_stats.json").read_text())
    m = [f"\\newcommand{{\\FrameMs}}{{{d['frame_ms']:.0f}}}",
         f"\\newcommand{{\\WindowMs}}{{{d['window_ms']:.0f}}}",
         f"\\newcommand{{\\ClipMs}}{{{d['clip_ms']:.0f}}}",
         f"\\newcommand{{\\ClipFrames}}{{{d['clip_frames']}}}",
         f"\\newcommand{{\\ClipVoxels}}{{{d['clip_voxels']:,}}}",
         f"\\newcommand{{\\NWindows}}{{{d['n_windows']:,}}}",
         f"\\newcommand{{\\VoxelRate}}{{{_sci(d['clip_voxel_rate'])}}}",
         f"\\newcommand{{\\SpikesPerClip}}{{{d['mean_spikes_per_clip']:.0f}}}",
         f"\\newcommand{{\\NTrain}}{{{d['split_counts']['train']}}}",
         f"\\newcommand{{\\NVal}}{{{d['split_counts']['val']}}}",
         f"\\newcommand{{\\NTest}}{{{d['split_counts']['test']}}}"]
    _write("preproc_macros.tex", "\n".join(m), "reports/preproc_stats.json")


def data_provenance() -> None:
    """The 31 recordings, their source, and what the archive does not say."""
    d = json.loads(Path("reports/data_provenance.json").read_text())
    rows = []
    for r in d["used"]:
        prep = "organoid" if r["dandiset"] == "000732" else "slice"
        rows.append(
            f"{r['assay_idx']} & {_esc(r['assay_name'].replace('_ecephys', ''))} & "
            f"{r['dandiset']} & {prep} & {_esc(r.get('subject_id', '--'))} & "
            f"{_esc(r.get('age', '--'))} & {_esc(r.get('sex', '--'))} & "
            f"{r.get('n_routed_channels', 0)} & {r.get('duration_s', 0):.0f} & "
            f"\\texttt{{{r.get('electrode_config_md5', '--')}}} \\\\")
    body = ("\\begin{tabular}{r l l l l l c r r l}\n\\toprule\n"
            "idx & recording & dandiset & prep. & subject & age & sex & "
            "chan. & dur.\\,(s) & routing \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("data_provenance.tex", body, "reports/data_provenance.json")

    # The counts the main text quotes, so §3 does not hand-type them either.
    by = d["by_preparation"]
    macros = [f"\\newcommand{{\\NAssays}}{{{d['n_used']}}}"]
    for k, v in by.items():
        tag = "Organoid" if "organoid" in k else "Slice"
        macros.append(f"\\newcommand{{\\N{tag}Assays}}{{{v}}}")
    cfgs = {r["dandiset"]: set() for r in d["used"]}
    for r in d["used"]:
        cfgs[r["dandiset"]].add(r.get("electrode_config_md5"))
    macros.append(f"\\newcommand{{\\NOrganoidRoutings}}{{{len(cfgs['000732'])}}}")
    macros.append(f"\\newcommand{{\\NSliceRoutings}}{{{len(cfgs['001132'])}}}")
    ch = [r["n_routed_channels"] for r in d["used"]]
    macros.append(f"\\newcommand{{\\ChanMin}}{{{min(ch)}}}")
    macros.append(f"\\newcommand{{\\ChanMax}}{{{max(ch)}}}")
    _write("data_macros.tex", "\n".join(macros), "reports/data_provenance.json")


def scalability() -> None:
    """Where each arm keeps its capacity: shared weights, or a per-assay table."""
    c = json.loads((EB / "param_census.json").read_text())["arms"]
    rows = []
    for key, label in ARMS:
        v = c.get(key)
        if v is None:
            continue
        fitted = v.get("fitted", v["shared"])
        rows.append(f"{label} & {fitted:,} & {v.get('shared_maps', 0):,} & "
                    f"\\textbf{{{v['per_assay']:,}}} & "
                    f"{v['per_assay'] * 1000:,} \\\\")
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "arm & fitted (shared) & shared maps & per assay & "
            "at 1000 assays \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t1_scalability.tex", body,
           "reports/external_baselines/param_census.json")


def generation() -> None:
    """The four generation families at full context, each with its own null.

    The bracketed value is that same arm's `random`-context score, so a cell
    whose value and null are close is not using its conditioning. Without it a
    reader cannot tell conditioning from an arm's default behaviour, which is
    exactly what the lookup arms do once their per-assay map is withheld.

    Source is `generation_families.json`, emitted by
    `external_baselines.diagnose_table --emit-families`. NOT comparison.json:
    that file's `per_clip` block holds nine per-clip statistics over seven
    pipeline variants, excludes both convolutional arms, and its
    stat_error_clean median is the conditioning-gain median rather than the
    glob+full value the paper quotes -- rendering from it would silently
    disagree with diagnostics.md.
    """
    src = EB / "generation_families.json"
    if not src.exists():
        raise SystemExit(
            f"{src} missing. Generate it with:\n"
            f"  python -m MAGVIT_project.external_baselines.diagnose_table "
            f"--emit-families\n"
            f"The four families exist only inside diagnose_table.py; do not "
            f"transcribe them from diagnostics.md.")
    d = json.loads(src.read_text())
    FULL, NULL = "global_full_local", "random"
    # Keys as diagnose_table's MODELS labels them, in the order the paper
    # argues. The dagger and the _ref_ marks travel with the label so a caption
    # cannot forget them.
    LABEL = [("Ours (4C+soft)", "Ours"),
             ("MaskGIT-flat", "MaskGIT-flat"),
             ("3D U-Net (det.)\u2020", "3D U-Net$^\\dagger$"),
             ("3D CVAE", "3D CVAE"),
             ("Dich. Gaussian", "\\emph{ref} DG"),
             ("Coupled GLM", "\\emph{ref} GLM")]

    rows = []
    for title, blk in d["families"].items():
        arrow = "$\\downarrow$" if blk["better"] == "low" else "$\\uparrow$"
        cells = []
        for raw, _lbl in LABEL:
            v = blk["arms"].get(raw)
            cells.append("--" if v is None else
                         f"{v[FULL]:.4f} \\emph{{[{v[NULL]:.3f}]}}")
        rows.append(f"{_esc_title(title)} {arrow} & " + " & ".join(cells)
                    + " \\\\")

    header = " & ".join(lbl for _, lbl in LABEL)
    body = ("\\begin{tabular}{l r r r r r r}\n\\toprule\n"
            f"family & {header} \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t3_generation_families.tex", body, str(src))


def task_completion() -> None:
    """Site-level and voxel-level AP on the four completion tasks.

    Two blocks of one table because they answer different questions -- which
    ELECTRODE fires, and whether the FRAME is right too -- and our result
    differs sharply between them. Nothing is bolded: 20 of the 32 paired tests
    go to another arm, so a bolded scoreboard would imply a competition this
    work does not win. Cells carry the paired-test verdict instead.

    Read WITHIN a column only. The ROI fraction differs by task
    (1.00 / 0.60 / 0.41 / 0.33), so the columns have different base rates.
    `recon` is free generation at zero context, not a fourth completion task.
    """
    src = EB / "cross_model_tests.json"
    d = json.loads(src.read_text())
    # The null is the point of the table, so it is a row and not a footnote:
    # `marginal` is the clip's own recording's per-site firing rate measured on
    # that recording's TRAIN clips and held constant in time -- no model, no
    # completion, no clip-specific information at all. Every learned arm loses
    # to it. `marginal_xa` withholds the clip's own recording, and the distance
    # between the two rows is how much of the first is memorisation.
    nulls = json.loads((EB / "task_eval_nulls.json").read_text())["tasks"]
    TASKS = ["recon", "causal", "noncausal", "spatial"]
    ARMLBL = {"MaskGIT-flat": "MaskGIT-flat",
              "3D U-Net (det.)": "3D U-Net$^\\dagger$",
              "3D CVAE": "3D CVAE"}
    MARK = {"pipeline": "$^{\\ast}$", "arm": "", "ns": "$^{\\circ}$"}

    ours, per_arm = {}, {}
    for r in d["rows"]:
        if r["arm"] not in ARMLBL:
            continue
        ours[(r["family"], r["task"])] = r["pipeline"]
        per_arm[(r["family"], r["task"], r["arm"])] = r

    blocks = []
    for fam, famlbl in (("site AP", "Site AP $\\uparrow$ --- which electrode"),
                        ("voxel AP",
                         "Voxel AP $\\uparrow$ --- which electrode \\emph{and} frame")):
        blocks.append(f"\\multicolumn{{5}}{{l}}{{\\textit{{{famlbl}}}}} \\\\")
        blocks.append("Ours & " + " & ".join(
            f"{ours[(fam, t)]:.4f}" for t in TASKS) + " \\\\")
        for arm, lbl in ARMLBL.items():
            cells = []
            for t in TASKS:
                r = per_arm.get((fam, t, arm))
                cells.append("--" if r is None
                             else f"{r['arm_value']:.4f}{MARK[r['verdict']]}")
            blocks.append(f"{lbl} & " + " & ".join(cells) + " \\\\")
        fld = "site_ap" if fam == "site AP" else "ap"
        for nk, nlbl in (("marginal", "\\emph{null} recording site map, seen"),
                         ("marginal_xa",
                          "\\emph{null} recording site map, unseen")):
            blocks.append(f"{nlbl} & " + " & ".join(
                f"{nulls[t]['arms'][nk][fld]:.4f}" for t in TASKS) + " \\\\")
        blocks.append("\\midrule")
    blocks.pop()

    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "arm & free gen.\\ (0) & causal (1) & noncausal (2) & spatial (3)"
            " \\\\\n\\midrule\n" + "\n".join(blocks)
            + "\n\\bottomrule\n\\end{tabular}")
    _write("t2_task_completion.tex", body, str(src))


def stage_prior_ladder() -> None:
    """Stage 4A motif prior against the four-rung null ladder.

    The strongest null is `assay_position` -- the empirical distribution of
    codes at that grid position within that recording. Beating `uniform` is
    worth nothing; the ladder exists so the reported margin is against the
    hardest available lookup, and `null_strongest_level` records which that is.

    Median rank, never mean: the distribution has a long tail and the mean
    (44.65) misrepresents the median (9.0).
    """
    src = Path("reports/evaluation_report_prior_4A_V961.json")
    d = json.loads(src.read_text())
    assert d["null_strongest_level"] == "assay_position", d["null_strongest_level"]
    rows = []
    for pre, lbl in (("null_uniform_z1", "uniform"),
                     ("null_global_z1", "global marginal"),
                     ("null_assay_z1", "per-recording marginal"),
                     ("null_assay_position_z1",
                      "per-recording $\\times$ position")):
        rows.append(f"{lbl} & {d[pre+'_acc']:.4f} & {d[pre+'_top5_acc']:.4f} & "
                    f"{d[pre+'_median_rank']:.0f} & {d[pre+'_mrr']:.4f} & "
                    f"{d[pre+'_ce']:.4f} \\\\")
    rows.append("\\midrule")
    rows.append(f"\\textbf{{motif prior (ours)}} & "
                f"\\textbf{{{d['flat_acc']:.4f}}} & "
                f"\\textbf{{{d['flat_top5_acc']:.4f}}} & "
                f"\\textbf{{{d['flat_median_rank']:.0f}}} & "
                f"\\textbf{{{d['flat_mrr']:.4f}}} & "
                f"\\textbf{{{d['loss_flat']:.4f}}} \\\\")
    body = ("\\begin{tabular}{l r r r r r}\n\\toprule\n"
            "predictor & top-1 $\\uparrow$ & top-5 $\\uparrow$ & "
            "median rank $\\downarrow$ & MRR $\\uparrow$ & "
            "CE (nats) $\\downarrow$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t4c_prior_nulls.tex", body, str(src))


def motif_reuse() -> None:
    """Is the alphabet shared across recordings? The thesis's own table.

    Only the RAREFIED overlap is rendered. The raw Jaccard in the same JSON
    tracks sampling effort at r = +0.96 and is explicitly marked unquotable by
    the analysis that produced it; putting it in a paper table would undo that.
    """
    src = Path("reports/analysis_motif_reuse.json")
    d = json.loads(src.read_text())
    e, jr = d["entropy"], d["jaccard_rarefied"]
    rows = [
        f"alphabet entries in use & {d['vocab_global']} of {d['V']} \\\\",
        f"used by $\\geq 5$ recordings, rarefied & "
        f"{d['shared_core']['used_by_ge_k_rarefied']['5']:.0f} \\\\",
        "\\midrule",
        f"$H(\\mathrm{{code}})$ & {e['H_code_mm']:.4f} nats \\\\",
        f"$H(\\mathrm{{code}} \\mid \\mathrm{{recording}})$ & "
        f"{e['H_code_given_recording_mm']:.4f} nats \\\\",
        f"\\textbf{{retained fraction}} & "
        f"\\textbf{{{e['reuse_ratio_mm']:.4f}}} \\\\",
        "\\midrule",
        f"rarefied overlap, within organoid & "
        f"{jr['mean_within_organoid']:.4f} \\\\",
        f"rarefied overlap, within slice & {jr['mean_within_slice']:.4f} \\\\",
        f"rarefied overlap, across preparations & "
        f"{jr['mean_cross_prep']:.4f} \\\\",
        f"\\emph{{null}} label-shuffled & {jr['null_mean']:.4f} "
        f"$\\pm$ {jr['null_sd']:.4f} \\\\",
    ]
    body = ("\\begin{tabular}{l r}\n\\toprule\n"
            "quantity & value \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t5_motif_reuse.tex", body, str(src))


def stage_contributions() -> None:
    """Stage 3 and the ladder: the two rows of T4 that are fully derivable."""
    s3 = json.loads(Path("reports/analysis_stage3_lct.json").read_text())
    last = s3[-1]
    rows = []
    for arm, label in (("lct", "\\texttt{lct} only"),
                       ("gct", "\\texttt{gct} only"),
                       ("both", "both")):
        v = last[arm]
        rows.append(f"{label} & {v['dnll_flat']:.4f} & {v['dnll_tex']:.4f} & "
                    f"{v['r2_tcent']:.4f} & {v['r2_tmarg']:.4f} \\\\")
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "conditioning & $\\Delta$NLL flat $\\uparrow$ & "
            "$\\Delta$NLL texton $\\uparrow$ & $R^2$ $t$-centroid $\\uparrow$ & "
            "$R^2$ $t$-marginal $\\uparrow$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t4b_stage3_lct.tex", body, "reports/analysis_stage3_lct.json")

    lad = json.loads(Path("reports/ablation_ladder_decode_depth.json").read_text())
    lv, inc = lad["levels"], lad["increments"]
    order = [("z1", "$z_1$", None),
             ("z1+z2", "$z_1{+}z_2$", "z1 -> z1+z2"),
             ("z1+z2+z3", "$z_1{+}z_2{+}z_3$", "z1+z2 -> z1+z2+z3")]
    rows = []
    for key, label, ikey in order:
        gain = "--"
        if ikey:
            g = inc[ikey]
            gain = (f"\\textbf{{$+${g['mean_delta']:.4f}}} "
                    f"({g['win_frac']*100:.0f}\\% of clips)")
        rows.append(f"{label} & {lv[key]['mean']:.4f} & {gain} \\\\")
    body = ("\\begin{tabular}{l r l}\n\\toprule\n"
            "decode depth & AP $\\uparrow$ & gain over previous \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t4a_ladder_depth.tex", body,
           "reports/ablation_ladder_decode_depth.json")


def main() -> int:
    preproc_macros()
    data_provenance()
    scalability()
    task_completion()
    generation()
    motif_reuse()
    stage_contributions()
    stage_prior_ladder()
    print("\nRemaining tables are trims of rendered blocks in "
          "reports/external_baselines/diagnostics.md; port them here as they "
          "are finalised so nothing in the paper is hand-typed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
