#!/usr/bin/env python3
"""Render the paper's tables to LaTeX from the committed report artifacts.

Same rule as `external_baselines/diagnose_table.py`: no number is typed into
prose or into a `.tex` file by hand. Every cell here is read from a JSON file in
`reports/`, so a table cannot drift from the run that produced it, and a
reviewer's question about any cell resolves to a file path.

    python tools/make_paper_tables.py

Writes paper/tables/*.tex, each a bare `tabular` meant to be `\\input` inside a
float, so the caption and label live with the surrounding text.
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("paper/tables")
EB = Path("reports/external_baselines")

# Display names, in the order the paper argues. Ours first, then the learned
# peer, then the two conv arms, then the lookups -- which are ceilings and are
# marked as such rather than being allowed to win a bolded comparison.
ARMS = [("pipeline", "Ours"), ("maskgit_flat", "MaskGIT-flat"),
        ("unet3d", "3D U-Net$^\\dagger$"), ("cvae3d", "3D CVAE"),
        ("dg", "\\emph{ref} Dich.\\ Gaussian"), ("glm", "\\emph{ref} Coupled GLM")]


def _esc(s: str) -> str:
    return str(s).replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")


def _write(name: str, body: str, source: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    p = OUT / name
    p.write_text(f"% GENERATED by tools/make_paper_tables.py from {source}\n"
                 f"% Do not edit by hand -- edit the source or the generator.\n"
                 f"{body}\n")
    print(f"wrote {p}")


def data_provenance() -> None:
    """The 31 recordings, their source, and what the archive does not say."""
    d = json.loads(Path("reports/data_provenance.json").read_text())
    rows = []
    for r in d["used"]:
        prep = "organoid" if r["dandiset"] == "000732" else "slice"
        rows.append(
            f"{r['assay_idx']} & {_esc(r['assay_name'].replace('_ecephys', ''))} & "
            f"{r['dandiset']} & {prep} & {_esc(r.get('subject_id', '--'))} & "
            f"{_esc(r.get('age', '--'))} & {_esc(r.get('sex', '--'))} & "
            f"{r.get('n_routed_channels', 0)} & {r.get('duration_s', 0):.0f} & "
            f"\\texttt{{{r.get('electrode_config_md5', '--')}}} \\\\")
    body = ("\\begin{tabular}{r l l l l l c r r l}\n\\toprule\n"
            "idx & recording & dandiset & prep. & subject & age & sex & "
            "chan. & dur.\\,(s) & routing \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("data_provenance.tex", body, "reports/data_provenance.json")

    # The counts the main text quotes, so §3 does not hand-type them either.
    by = d["by_preparation"]
    macros = [f"\\newcommand{{\\NAssays}}{{{d['n_used']}}}"]
    for k, v in by.items():
        tag = "Organoid" if "organoid" in k else "Slice"
        macros.append(f"\\newcommand{{\\N{tag}Assays}}{{{v}}}")
    cfgs = {r["dandiset"]: set() for r in d["used"]}
    for r in d["used"]:
        cfgs[r["dandiset"]].add(r.get("electrode_config_md5"))
    macros.append(f"\\newcommand{{\\NOrganoidRoutings}}{{{len(cfgs['000732'])}}}")
    macros.append(f"\\newcommand{{\\NSliceRoutings}}{{{len(cfgs['001132'])}}}")
    ch = [r["n_routed_channels"] for r in d["used"]]
    macros.append(f"\\newcommand{{\\ChanMin}}{{{min(ch)}}}")
    macros.append(f"\\newcommand{{\\ChanMax}}{{{max(ch)}}}")
    _write("data_macros.tex", "\n".join(macros), "reports/data_provenance.json")


def scalability() -> None:
    """Where each arm keeps its capacity: shared weights, or a per-assay table."""
    c = json.loads((EB / "param_census.json").read_text())["arms"]
    rows = []
    for key, label in ARMS:
        v = c.get(key)
        if v is None:
            continue
        fitted = v.get("fitted", v["shared"])
        rows.append(f"{label} & {fitted:,} & {v.get('shared_maps', 0):,} & "
                    f"\\textbf{{{v['per_assay']:,}}} & "
                    f"{v['per_assay'] * 1000:,} \\\\")
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "arm & fitted (shared) & shared maps & per assay & "
            "at 1000 assays \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t1_scalability.tex", body,
           "reports/external_baselines/param_census.json")


def generation() -> None:
    """The four generation families at full context, each with its own null.

    The bracketed value is that same arm's `random`-context score, so a cell
    whose value and null are close is not using its conditioning. Without it a
    reader cannot tell conditioning from an arm's default behaviour.
    """
    src = EB / "comparison.json"
    d = json.loads(src.read_text())
    ref = d["reference"]
    fams = [("stat_error_clean", "A. Conditional accuracy $\\downarrow$")]
    rows = []
    for key, label in fams:
        arms = d["per_clip"].get(key, {})
        cells = [f"{arms[ref]['median']:.4f}"]
        for name in ("MaskGIT-flat", "DG (Macke'09)", "GLM (Pillow'08)"):
            v = arms.get(name)
            cells.append("--" if v is None else f"{v['median']:.4f}")
        rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "metric & Ours & MaskGIT-flat & \\emph{ref} DG & \\emph{ref} GLM "
            "\\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t3_generation_perclip.tex", body, str(src))


def stage_contributions() -> None:
    """Stage 3 and the ladder: the two rows of T4 that are fully derivable."""
    s3 = json.loads(Path("reports/analysis_stage3_lct.json").read_text())
    last = s3[-1]
    rows = []
    for arm, label in (("lct", "\\texttt{lct} only"),
                       ("gct", "\\texttt{gct} only"),
                       ("both", "both")):
        v = last[arm]
        rows.append(f"{label} & {v['dnll_flat']:.4f} & {v['dnll_tex']:.4f} & "
                    f"{v['r2_tcent']:.4f} & {v['r2_tmarg']:.4f} \\\\")
    body = ("\\begin{tabular}{l r r r r}\n\\toprule\n"
            "conditioning & $\\Delta$NLL flat $\\uparrow$ & "
            "$\\Delta$NLL texton $\\uparrow$ & $R^2$ $t$-centroid $\\uparrow$ & "
            "$R^2$ $t$-marginal $\\uparrow$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t4b_stage3_lct.tex", body, "reports/analysis_stage3_lct.json")

    lad = json.loads(Path("reports/ablation_ladder_decode_depth.json").read_text())
    lv, inc = lad["levels"], lad["increments"]
    order = [("z1", "$z_1$", None),
             ("z1+z2", "$z_1{+}z_2$", "z1 -> z1+z2"),
             ("z1+z2+z3", "$z_1{+}z_2{+}z_3$", "z1+z2 -> z1+z2+z3")]
    rows = []
    for key, label, ikey in order:
        gain = "--"
        if ikey:
            g = inc[ikey]
            gain = (f"\\textbf{{$+${g['mean_delta']:.4f}}} "
                    f"({g['win_frac']*100:.0f}\\% of clips)")
        rows.append(f"{label} & {lv[key]['mean']:.4f} & {gain} \\\\")
    body = ("\\begin{tabular}{l r l}\n\\toprule\n"
            "decode depth & AP $\\uparrow$ & gain over previous \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
    _write("t4a_ladder_depth.tex", body,
           "reports/ablation_ladder_decode_depth.json")


def main() -> int:
    data_provenance()
    scalability()
    generation()
    stage_contributions()
    print("\nRemaining tables are trims of rendered blocks in "
          "reports/external_baselines/diagnostics.md; port them here as they "
          "are finalised so nothing in the paper is hand-typed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
